### ISSUE TITLE
NLX breaks LDAP Connector testing

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/auth0-custom-lock#10]
```
if ( window.location.hostname !== 'localhost' ) {
    var w = window.location.toString();
    if ( w.indexOf('tried_silent_auth=true') === -1 ) {
       /* Only works with LDAP at this time */
       window.location = w.replace('/login?', '/authorize?').replace('?client=', '?client_id=') + '&sso=true&connection=Mozilla-LDAP-Dev&tried_silent_auth=true'
     }
```

This forces the `connection` parameter which makes tests fail in auth0's LDAP connector test functionality (it calls the login page and fails as the connection is hard coded while their tests expect this not to be the case / they hardcode it elsewhere)

you can reproduce in the dashboard by going to enterprise connections => ad/ldap and click the mozilla conector, then the little "try" arrow

**Comment by hidde** [comment]
This is now fixed in #16.
