### ISSUE TITLE
Create new settings page in NLX with autologin preference

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/auth0-custom-lock#101]
In order to enable users to assert if they want the auto-login behavior enabled or disabled, we should probably create a settings page in the NLX.

This would be a new page ("page" like how the UI with social buttons is a page, and the UI where you enter your password is a different "page") that the user could navigate to from the main page (where the social buttons and email address textbox are), probably with a understated link on the main page.

This settings page would initially have at least a checkbox/button/whatever that the user could click to enable or disable autologin. This enabling and disabling would then be stored in localStorage and would later direct NLX how to behave when a user hits it (attempt autologin or show the main page).

This may also be a good place to put the "global logout" button that's currently on the SSO dashboard to enable the user to logout of their Auth0 session. Maybe this one should be elsewhere, not sure.

# Other thoughts

This feature depends upon solving the #58 problem of localStorage being emptied intermittently and unexpectedly

**Comment by hidde** [comment]
We could potentially also send users to this page from SSO Dashboard, so that the checkbox idea in SSO Dashboard would essentially be a link to NLX with a specific parameter.

**Comment by hidde** [comment]
This has now been implemented in NLX 1.3.0, which went live yesterday!
