### ISSUE TITLE
Move /connections call to beginning of execution to speed up autologin

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/auth0-custom-lock#106]
For NLX autologin, currently the whole NLX page must first be loaded (500KB), then once it's loaded, the call to the `/connections` endpoint needs to be made and then the autologin redirect can be returned.

Since the `/connections` call appears to currently be a required call before *all* autologin and non-autologin NLX calls, can we move this to the very beginning of page execution (before loading libraries) so that we can immediately bypass the page load and go to autologin if the connection type is supported?

This would potentially obviate the need for the spinner since the autologin would be fast.

**Comment by hidde** [comment]
Related to #32 ?

**Comment by hidde** [comment]
Closing this. With [our new CSP](https://github.com/mozilla-iam/auth0-custom-lock/issues/149) that disallows inline, splitting into two external files did not seem to make it faster, so I have left it the way it is. For most returning users this file will now be served from cache, which should give a good performance improvement.
