### ISSUE TITLE
Auto redirect when logged in only supports LDAP

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/auth0-custom-lock#11]
```
      if ( window.location.hostname !== 'localhost' ) {
        var w = window.location.toString();
        if ( w.indexOf('tried_silent_auth=true') === -1 ) {
          /* Only works with LDAP at this time */
          window.location = w.replace('/login?', '/authorize?').replace('?client=', '?client_id=') + '&sso=true&connection=Mozilla-LDAP-Dev&tried_silent_auth=true'
        }
      }
     </script>
```

This should use connection=%last-used-connection. Since there is now code for this, i'd just store the connection in localStorage and use that

**Comment by gdestuynder** [comment]
See also https://github.com/mozilla-iam/auth0-custom-lock/issues/9 which is similar though different

**Comment by gdestuynder** [comment]
Could also fix https://github.com/mozilla-iam/auth0-custom-lock/issues/10 by fixing this :)

**Comment by hidde** [comment]
All connection methods are supported when [PR 16](https://github.com/mozilla-iam/auth0-custom-lock/pull/16) is merged in.
