### ISSUE TITLE
Error page after verifying firefox accounts 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/auth0-custom-lock#112]
STR:
1. Navigate to https://testrp.security.allizom.org/.
2. Click first "Sign In" grey button (which has fxa available).
3. Click "Log in with Firefox Accounts" -> FXA create an account page is shown.
4. Enter an email + Password 2 times + age (>13) and click Create account button. -> Message asking to check your email is shown. 
5. Open a new tab, navigate to your email provider and click the "Verify your Firefox Accounts" email. 
6. Click the "Activate Now" button from the email. -> New tab saying "Account Verified" is shown
7. Navigate back to the tab you left off in step 4.

Result:
"Oye, something went wrong" error page shown, with token https://pastebin.mozilla.org/9082430. 

I don't know exactly what should be expected behavior here.

**Comment by gdestuynder** [comment]
@viorelaioia does this still happen? Am not able to get that message. i suspect we might have fixed it along the way, but not sure

**Comment by viorelaioia** [comment]
@gdestuynder , this is not happening anymore. Now I'm getting the "You must setup a security device("MFA, "2FA") for your Firefox Account" message, which makes sense, as I don't have 2fa setup for my fxa. Closing the ticket.
