### ISSUE TITLE
Cannot login passwordless

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/auth0-custom-lock#123]
STR:

   1. Navigate to mozillians staging
   2. Click Log in button
   3. Add a non-LDAP email address and click Enter

Expected:
"Send email" screen is shown

Actual:
Spinning spinner is shown continuously 
![spinner](https://user-images.githubusercontent.com/5293100/39229609-237d9314-486c-11e8-8b2f-878053ea84cc.png)

**Comment by viorelaioia** [comment]
CC: @hidde

**Comment by hidde** [comment]
Fixed!

**Comment by viorelaioia** [comment]
Works as expected!
