### ISSUE TITLE
Github / google last used login is remembered after sso logout in Edge/IE 11

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/auth0-custom-lock#124]
Issue is reproducible in Edge and Internet Explorer 11

STR:
1. Login to sso dashboard with github
2. In a new tab, navigate to mozillians staging and click Login button => user is autologged in with github
3. Logout from mozillians
4. Logout from sso dasboard
5. Go to mozillians staging and click Login button

Expected:
Fresh nlx is shown, user needs to enter credentials to login again

Actual:
User is autologged in with github

Note:
This is happening with github and google login. LDAP works as expected

**Comment by hidde** [comment]
This issue occurs specifically when still having Mozillians open in a tab. That tab will not know that autologin method was removed, a new tab will.

It seems that this is an IE11/Edge specific issue and possibly a bug in their rendering engine.

Moving this issue to 'PRIORITY-LOW (BACKLOG)' as we have <1% users on IE11/Edge.

**Comment by hidde** [comment]
Because the above reasons are still true, I'll mark this issue as `WONTFIX ` and close it.
