### ISSUE TITLE
[dev] Floating label overlaps browser saved email value

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/auth0-custom-lock#134]
STR:
1. Have saved login credentials in your browser for https://auth-dev.mozilla.auth0.com
1. Navigate to https://social-pwless.testrp.security.allizom.org
2. Click email input field and select the saved email value
3. Click outside the email input field

Expected:
Nothing happens.

Actual:
The floating label overlaps the selected value in the email field.

This is also happening for the password field, when pasting the password. 
See [video](https://drive.google.com/file/d/1py0OoUuKnVeU8nxYAJI208mAitlscAy5/view?usp=sharing)
![email1](https://user-images.githubusercontent.com/5293100/39995122-1da8c0b8-5784-11e8-8c08-111c007943f6.jpg)
![password](https://user-images.githubusercontent.com/5293100/39995148-29522a44-5784-11e8-85da-dd46c3b12d3e.jpg)

**Comment by viorelaioia** [comment]
This is still happening

**Comment by hidde** [comment]
In which browser is this happening?

**Comment by viorelaioia** [comment]
Just verified and this is not reproducible anymore. Closing the issue.
