### ISSUE TITLE
Add space for password floating label when error message shown

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/auth0-custom-lock#135]
STR:
1. Navigate to sso.allizom.org
2. Enter mozilla email ldap in email field then click Enter
3. Enter a wrong password

Result: Error message is shown, the password label seems too close from the error message above. Maybe we can add more space between them. @m-branson , what is your opinion here? 
<img width="775" alt="screen shot 2018-05-14 at 12 45 45" src="https://user-images.githubusercontent.com/5293100/40001651-5e6918b0-5797-11e8-9544-26aeaf9d5757.png">

Also, @m-branson , @hidde , it is intended to have the text "Or login with" removed from nlx (for social options) ? Just wanna make sure. Thanks!

**Comment by m-branson** [comment]
>Maybe we can add more space between them. @m-branson , what is your opinion here?
Yes please :) @viorelaioia we should need additional padding on all field instances, appreciate your eyes helping us fine tune this.

>Also, @m-branson , @hidde , it is intended to have the text "Or login with" removed from nlx (for social options) ?
Yes! We're going to utilize `Log in with GitHub` and `Log in with Google`. The additional "Or log in with:" title was creating too much verbiage on the screen. Looking to keep it simple and clear for our users without too much additional eye scanning needed.

@hidde in @viorelaioia's screenshot above the `x` icon is missing, is this a staging issue? If not, can we get that in place?

**Comment by hidde** [comment]
> Yes please :) @viorelaioia we should need additional padding on all field instances, appreciate your eyes helping us fine tune this.

I missed this one. Will fix!

> Yes! We're going to utilize Log in with GitHub and Log in with Google. The additional "Or log in with:" title was creating too much verbiage on the screen. Looking to keep it simple and clear for our users without too much additional eye scanning needed.

Yes, with the caveat that ‘Log in with Firefox Account’ does not fit, and we're changing this to 'Log in with Firefox' 

> @hidde in @viorelaioia's screenshot above the x icon is missing, is this a staging issue? If not, can we get that in place?

 Will double check

**Comment by hidde** [comment]
Double-checked, it does fit, but leaves little whitespace: 

<img width="369" alt="screenshot of 3 buttons" src="https://user-images.githubusercontent.com/178782/40010145-c9157eb8-5758-11e8-839b-6dcf38361a90.png">

On very small screens, it goes over two lines:

<img width="266" alt="screenshot of 3 buttons, firefox button over 2 lines" src="https://user-images.githubusercontent.com/178782/40010186-e3a47216-5758-11e8-95f2-e25e4bcdcfa2.png">

**Comment by gdestuynder** [comment]
We'd have to confirm FxA branding if we can use "Login with Firefox" (ie without account) though they might also have better ideas. Note, when I do this I just ask on #fxa :)

**Comment by hidde** [comment]
I've just added extra space in case there's a paragraph of text above the floating label. Also fixed the icon in front of the error and updated the text to say ‘Login with $method’

<img width="319" alt="screenshot; label has space to float, error icon is fixed src="https://user-images.githubusercontent.com/178782/40028570-7025d672-5794-11e8-8b62-0ade982db49b.png">

Updated version is now in Auth0-DEV

**Comment by vladikoff** [comment]
> We'd have to confirm FxA branding if we can use "Login with Firefox" (ie without account) though they might also have better ideas. Note, when I do this I just ask on #fxa :) (ie if im not around you can ask directly)

@ryanfeeley is on PTO. I think we should ask @phlsa about this instead


cc @rfk

**Comment by vladikoff** [comment]
ping @designakt , seems like Ryan left you in charge of this while on PTO :)

**Comment by designakt** [comment]
I checked with Michelle from Content Strategy, and for this context it is OK to use "Firefox" instead of "Firefox Accounts" as it is implied that this is talking about various accounts.
For the buttons shown above, please either say "Log in with" in each button, or once on top, but please do not mix, as shown in [this comment](https://github.com/mozilla-iam/auth0-custom-lock/issues/135#issuecomment-388878649)

![screenshot-2018-5-16 mozilla login 1](https://user-images.githubusercontent.com/8145891/40117906-a1baa480-5918-11e8-9f43-ac9c7c08e85f.png)
or
![screenshot-2018-5-16 mozilla login](https://user-images.githubusercontent.com/8145891/40117905-a19d52b8-5918-11e8-969d-66cfe6425d2a.png)

**Comment by hidde** [comment]
Thanks @designakt, that's great! Just to reassure, my earlier comment was a quick mock-up in which I had not adjusted all buttons. We will be sure not to mix these two styles, we'll go the ‘Log in with… ’ route for each button. 

@viorelaioia could you please verify if space between floating label and text + the icon now appear as expected?

**Comment by viorelaioia** [comment]
Looks good! Just one more small UI question. When no social login method is available, between Enter button and autologin toggle there are 2 gray lines shown, which are supposed to differentiate between sections in nlx. Do we want to keep them in this case? CC @m-branson , @hidde 

![screenshot-2018-5-17 mozilla login](https://user-images.githubusercontent.com/5293100/40176311-a5754334-59e3-11e8-94d0-529b375d9d43.png)

**Comment by m-branson** [comment]
>I checked with Michelle from Content Strategy, and for this context it is OK to use "Firefox" instead of "Firefox Accounts" as it is implied that this is talking about various accounts.

Thanks @designakt and @vladikoff for the quick feedback here, much appreciated. 🥇
