### ISSUE TITLE
Auth0 dev test RPs have more available login options than they should

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/auth0-custom-lock#137]
STR:
1. Navigate to https://testrp.security.allizom.org/
2. Click the 4th "Sign In" button - RP that has only LDAP option available

Expected:
Only LDAP login option is displayed.

Actual:
LDAP, FxA and Google login options are displayed.

Note:
Same happens if I navigate to the RP that has only email and LDAP options available. 

![ldap only](https://user-images.githubusercontent.com/5293100/40049204-c1294ac4-583c-11e8-9d21-7761d7be0fdd.png)
![ldap pwless only](https://user-images.githubusercontent.com/5293100/40049212-c7691a68-583c-11e8-8c32-069bf9988124.png)

I'm not sure it this is a testrp config issue or an nlx issue, so I'm CC'ing both @gdestuynder and @hidde.

**Comment by gdestuynder** [comment]
![image](https://user-images.githubusercontent.com/956866/40074968-fe98c8b0-582f-11e8-82a6-380ef81f19fe.png)
![image](https://user-images.githubusercontent.com/956866/40075031-23a54cdc-5830-11e8-930b-8e78e73a49bf.png) (Fxa)

looks disabled in auth0, so it seems to be an NLX issue
