### ISSUE TITLE
Questions on nlx settings screen

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/auth0-custom-lock#140]
After logging into sso dashboard, and clicking "Enable / Disable Auto-login", this is how the settings screen looks like:
![settings screen](https://user-images.githubusercontent.com/5293100/40227272-b09f3af4-5a96-11e8-8338-6076c64e9b09.png)

I have a couple of questions:

1. Can we show the RP name below logo (for consistency reasons)?
2. Why do we show the "Need to log in with a different account?" link? Asking cause the user is already logged in, so it's a bit confusing to have the option to login again from the settings screen. 

CC: @hidde , @m-branson

**Comment by hidde** [comment]
> Can we show the RP name below logo (for consistency reasons)?

We could, but that would always be sso.mozilla.org, would that not be weird?

> Why do we show the "Need to log in with a different account?" link? Asking cause the user is already logged in, so it's a bit confusing to have the option to login again from the settings screen.

You are right, this will let usere log in again. I think this is useful, as it effectively lets them switch their auto-login method. What do you think?

**Comment by viorelaioia** [comment]
> You are right, this will let usere log in again. I think this is useful, as it effectively lets them switch their auto-login method. What do you think?

I found it confusing to be able to login with a new account when on settings page, as you actually didn't log out from your existing account. I would need @m-branson's opinion here, as I'm not sure what are user's expectations here.

**Comment by m-branson** [comment]
>Can we show the RP name below logo (for consistency reasons)?

>>We could, but that would always be sso.mozilla.org, would that not be weird?

I don't see the harm in confirming for our users that they are currently in `sso.mozilla.org` -- Provides context as they move between screens.

>You are right, this will let usere log in again. I think this is useful, as it effectively lets them switch their auto-login method. What do you think?

>> I found it confusing to be able to login with a new account when on settings page, as you actually didn't log out from your existing account. I would need @m-branson's opinion here, as I'm not sure what are user's expectations.

@hidde this goes back to our initial conversation where I was concerned that we should make this a button that says `Log out of Mozilla` (similar to the SSO log out page). It breaks the mental model if we use the same text link as the login flow, as users aren't going through a login process, but rather editing a setting. If the function of that link is to log a user out and route them to the NLX start screen, then this should be surfaced to the user as a `Log out of Mozilla` button (centered at the bottom of the card.

**Comment by hidde** [comment]
> I don't see the harm in confirming for our users that they are currently in sso.mozilla.org -- Provides context as they move between screens.

OK, will update (in next version)! 

Re: ‘Need to log in with a  different account’ vs ‘Log out of Mozilla’
- In the current situation, the button takes user to the ‘initial’ screen of NLX, where they can (choose to) perform a log in _with a different method_ which effectively kills their current session and creates a new one. 
- ‘Log out’ would take user to sso.mozilla.com/logout, which then would redirect to NLX (for clearing autologin settings), which then would redirect to sso.mozilla.com signout page. 

‘Log out’ is a feature SSO Dashboard already has, switching account is one that currently does not exist, and I feel it is a useful addition for people with multiple login methods. To me, the wording (‘log in with a different account’) seems general enough to also make sense for this use case.

@m-branson: with this in mind, would you like to keep the button as it, change to a log out button or maybe remove it from the settings page altogether?

**Comment by m-branson** [comment]
> ‘Log out’ is a feature SSO Dashboard already has, switching account is one that currently does not exist, and I feel it is a useful addition for people with multiple login methods. To me, the wording (‘log in with a different account’) seems general enough to also make sense for this use case.

Great point, agreed. I remember now why we chose to keep it this way. I'm good with leaving as is (and watching user behavior to ensure success here -- in reality an account switcher at the SSO dashboard level would be better heuristically, perhaps in the future?) @viorelaioia what do you think?

**Comment by viorelaioia** [comment]
> @viorelaioia what do you think?

I don't have a strong opinion on this, I just wanna make sure we are on the same page. 
I will close the ticket as we agreed to add RP name and leave the "Need to log in with a different account?" link. Thanks @m-branson and @hidde !
