### ISSUE TITLE
Cannot login with different account if clicking link from nlx settings page

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/auth0-custom-lock#141]
STR:
1. Login to sso.allizom.org with mozilla LDAP
2. Click user avatar, then "Enable / Disable Auto-login" menu item
3. Click "Need to log in with a different account?" link
4. Select "Login with github" in the next screen
5. Enter github credentials and 2fa code

Expected:
User is successfully logged in with github

Actual:
User is redirected to a page with url "localhost:5000". Same issue if trying to login with google or fxa instead. If trying to login with LDAP, "Invalid State" error is shown after entering password. 

![error page](https://user-images.githubusercontent.com/5293100/40296230-b92160bc-5ce4-11e8-81d6-82c4864c2765.png)

**Comment by hidde** [comment]
Making this re-login work was a bit optimistic from my side; the set of data we need for a login request is larger than what this settings screen knows about and bringing more of these parameters to NLX would almost be circumventing standard OIDC flows, so this button has been removed.

A ‘log out’ button in the future would provide the same functionality as someone who logs out can log back in with a (different) method of their choice.
