### ISSUE TITLE
Error page when trying to login with fxa

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/auth0-custom-lock#143]
When clicking the "Login with Firefox" button on mozillians staging, user is redirected to error page shown below.
 
![login with fxa](https://user-images.githubusercontent.com/5293100/40369552-da0c028e-5de6-11e8-9d4a-2d950be4e9ea.png)

CC: @gdestuynder

**Comment by gdestuynder** [comment]
it looks like an fxa staging bug (dev.lcip.org domain), ie i suspect this will go away 

note: we'll switch to prod (accounts.firefox.com) as soon as the 2FA option is officially available

**Comment by viorelaioia** [comment]
Not reproducible anymore
