### ISSUE TITLE
Cannot login to mozillians staging 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/auth0-custom-lock#147]
STR: 
1. Navigate to mozillians staging
3. Click "Log In/Sign Up" button
4. Enter Ldap email, then click "Enter" button
5. Enter Ldap pass then click "Enter" button

Expected:
Duo page is shown

Actual:
Spinner is shown for some seconds, the mozillians staging homepage is shown. See [video](https://drive.google.com/file/d/1QSmfuEskhbC6Agq4L263fwOhxXwwHtUY/view?usp=sharing)

Note:
I cannot login with github either.
This is happening for sso.allizom.org also.

**Comment by hidde** [comment]
Something wasn't caching properly on the Auth0-side, this is now fixed!
