### ISSUE TITLE
"Log in with email" floats up on each NLX 1.4.0 login display

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/auth0-custom-lock#154]
When you visit the NLX 1.4.0, the page renders and then the "Log in with email" floats from inside the text box field up to above the field.

Also, it changes font and color.

https://www.youtube.com/watch?v=F2yUjmaK5pg

I suspect this was intended so that as the user looks at the NLX, they see what's supposed to go in the text box, then when they click, the hint moves out of the way, up above the box.

However, with the NLX auto focusing the text box, each time the NLX is loaded, the page starts with this text floating through the line around the textbox.

I don't know if the user would ever trigger this happening since I think the NLX autofocuses the text box each time it's loaded.

Anyhow, this looks weird as it's not user initiated. We should start the page with the text box focused and the hint above the box

**Comment by m-branson** [comment]
>I suspect this was intended so that as the user looks at the NLX, they see what's supposed to go in the text box, then when they click, the hint moves out of the way, up above the box.

Yes, indeed. Agreed that this undesirable when the text box is focused. _sighs_

In an ideal world my UX brain has it both ways: users who prefer a focused experience get it without the animation; and users who a_ren't even aware that focused states are a thing_ can understand what/why/how to use an entry field.

All of that said, I do believe that what @gene1wood is recommending here is the best way to go.
>Anyhow, this looks weird as it's not user initiated. We should start the page with the text box focused and the hint above the box

@hidde there is absolutely no way to disable animation for focused states and still provide an accessibility friendly experience?

BTW, thank you both for the detail oriented back and forth.

**Comment by hidde** [comment]
To clarify: clicking in the field is a focus in the technical sense of the word. Hence the behaviour as it happens. 

Would it be ok if it doesn’t animate when you click the field either? In that case we can definitely disable the animation. 

Another alternative would be to always have the label above (whether input has focus or not) and only change the input’s border color on focus. This was also recommended by the moz accesssibility folks when I reached out to them for a general check (but it does take more space / more clutter, so maybe cognitively less accessble?)

**Comment by m-branson** [comment]
Thanks @hidde, I recommend the following: 

- disable the float animation
- leave the label text within the form field when inactive (or as default state)
- if the field is focused / clicked the label should move above, but without the float animation

I believe this will provide user context across use cases while also ensuring an accessible experience. If there are other accessibility concerns around the text within the form field let me know. (Curious why moving the label above is more accessible in an inactive state.)

Side note, I met the moz accessibility team last week! Feel free to loop me into any convos across channels where helpful. :)

**Comment by hidde** [comment]
(Sorry my commit closed the issue, it will soon actually be live)

I've disabled the float animation.

The biggest accessibility issue with text inside an input functioning as its label is that the text is gone once someone starts typing, but we take care of that by floating it above. Other issues with it in some implementations is that the text inside the input is usually in a grey that is slightly too light, again, we've taken care of this 💯 .

Thanks Megan, and I will be sure to loop you in when discussing on public channels!
