### ISSUE TITLE
Once a user chooses Google or GitHub auth, they cannot go back and all future logins skip the lock and go straight to Google or GitHub

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/auth0-custom-lock#17]
# Pre-requisites

* A GitHub account which you've previously granted the old required OAuth scope of "Access user email addresses (read-only)" to the "Mozilla Dev Identity and Access Management" GitHub app but which you've not yet granted the new "Profile information (read-only)" scope

# Steps to reproduce

1. Browse to https://moderator.mozilla.org/oidc/authenticate/
2. On the NLX, click "GitHub"
3. On the GitHub OAuth scope authorization page click back

# Expected results

The user is taken back to the lock to choose a different login method

# Actual resultes

The user remains on the GitHub authorization page. Worse, if the user then just tries to browse again to the site by going to https://moderator.mozilla.org/oidc/authenticate/ they are immediately sent to the GitHub authorization page, so there's no apparent way to get out of this locked state.

**Comment by gdestuynder** [comment]
@hidde i think you might have this already filed somewhere

**Comment by gene1wood** [comment]
This happens for Google as well described in #18

**Comment by hidde** [comment]
Thanks for filing this. I was aware of it, but hadn't filed an issue yet.

**Comment by hidde** [comment]
Weird question maybe; it is possible to have a rule in place that requires a login prompt whenever someone has left their most recent GitHub login/signup attempt unfinished?

**Comment by hidde** [comment]
I have reverified, this is now better:

* with autologin turned on, pressing 'Back' while on GitHub/Google auth page will send you back to NLX, then you see autologin spinner and are sent back to GitHub/Google auth page. However if you manually visit https://moderator.mozilla.org/oidc/authenticate/  again, you get a fresh NLX and are out of the 'locked' state
* with autologin turned off, you are not auto-sent back to GitHub/Google auth page, so it works as expected

I think with that, we could consider this issue fixed?

@viorelaioia could you verify things are now working correctly for Google and GitHub?

**Comment by viorelaioia** [comment]
The behavior @hidde described above is correct. I believe we can consider this fixed, as we have a solution to get fresh nlx even when autologin is enabled.
