### ISSUE TITLE
SSO staging logout returns error page

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/auth0-custom-lock#174]
**STR:**
1. Login to sso.allizom.org
2. Click user avatar, then click Logout button from the menu

**Expected:**
"Log Out Success" message shown.

**Actual:**
Error page displayed, url is "https://auth-dev.mozilla.auth0.com/v2/logout?returnTo=https://sso.allizom.org/signout.html"

![logout error](https://user-images.githubusercontent.com/5293100/41655936-21e913dc-7497-11e8-87e2-e13f38e6cc98.png)

**Comment by gene1wood** [comment]
I can confirm that I get this with my account as well.

**Comment by hidde** [comment]
This was due to an update to the DEV tenant, it has now been fixed
