### ISSUE TITLE
Use proper names for connections

### ISSUE THREAD

**Issue by hidde** [mozilla-iam/auth0-custom-lock#179]
We currently use connection's identifiers in NLX, for example to display ‘Currently auto-logging in with…’. Those are lowercase strings with no spaces.

Let's map those identifiers to proper names somewhere, for example google-oauth2 --> Google, github --> GitHub (as [requested](https://bugzilla.mozilla.org/show_bug.cgi?id=1465640) by lasr21). 

So when this is fixed you should see ”Attempting auto-login with GitHub” instead of ”Attempting auto-login with github”.

cc @hmitsch

**Comment by viorelaioia** [comment]
I'd suggest to change "Attempting auto-login with Google Accounts" to "Attempting auto-login with Google". Thanks!
