### ISSUE TITLE
Direct users to go to their inbox to continue

### ISSUE THREAD

**Issue by hidde** [mozilla-iam/auth0-custom-lock#181]
Finding from usability report: 

> Users require more direction on email sent success screen
>
> Some testers stumbled on the email sent success screen. They understood they were sent an email, > but hesitated before going to their inbox to check it. 

And the recommendation:

> Include an additional line of text on the email sent success screen directing users to go to their inbox > to continue login.

Current text is:

> Email sent to [email], your login link will expire in 15 minutes. 

Maybe we can add this: 

> Please open your email to continue login.

cc @m-branson

**Comment by m-branson** [comment]
Hi @hidde thanks for working through these tasks :)

>Maybe we can add this:
>>Please open your email to continue login.

How about we refine to:
>Email sent to [email], go to your inbox to continue.
Your login link will expire in 15 minutes.

Thoughts?

**Comment by hidde** [comment]
This sounds great, I'll update this!
