### ISSUE TITLE
Cannot login with contributor LDAP account

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/auth0-custom-lock#188]
STR:
1. Navigate to mozillians.org 
2. Enter volunteer ldap email address in email field

Expected:
Password window is shown.

Actual:
"Send me an email" window is displayed. Contributor LDAP is seen as non-ldap, so passwordless flow window is returned. 

Note: This is happening for all Mozilla properties.

**Comment by hidde** [comment]
This is caused by Person API calls being blocked by our Content Security-Policy, in prod config it was accidentally set to .org domain (but in prod it is .com)

Fixed in this PR: https://github.com/mozilla-iam/auth0-custom-lock/pull/187

Let’s roll out asap.

**Comment by andrewkrug** [comment]
Fixed the CSP manually.

**Comment by viorelaioia** [comment]
Contributor LDAP login works as expected now! Closing the issue.
