### ISSUE TITLE
Add maintenance banner

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/auth0-custom-lock#194]
Add a maintenance banner that is optionally enabled with an NLX configuration variable.

This allows to quickly show a message that indicates we're aware of any problem going on with authentication. See also https://github.com/mozilla-iam/auth0-custom-lock/issues/193 for a better version of this.

In the mean time, proposing a banner that uses our current banner UI, with the message:
"We are currently experiencing issues and are working on resolving them as soon as possible. Please try to login again in a few minutes. If you have a specific issue, please contact <moc@mozilla.com>. Thank you for your understanding."

**Comment by hidde** [comment]
Ok, I'll add a config variable that enables a notification banner.

I would suggest to also have this outside the NLX CI/CD, so that it can also be used when there is a problem with the NLX CI/CD itself.

_Proposal_: let's also create a static page, host it somewhere (maybe SSO Dashboard for simplicity) and point NLX there if there is a problem?

**Comment by gdestuynder** [comment]
i think we could just have a static page that looks like NLX with the maintenance message and we can copy paste it in place, and/or 302 to it (such as, even, just a commented out line that just does a window.location(static page);
return; and bails, so that we can quickly enable it or copy paste it if everything goes horribly wrong)

Note: im suggesting this because normally all updates are zero-downtime, so the only time when we need this page is when CI/CD fails and NLX fails and we have to manually trigger it

@andrewkrug may have other ideas as well

**Comment by m-branson** [comment]
From our conversations today, it seems we're aligned that a maintenance page may be unnecessary at this point & a banner will do the job.

@hidde for the banner, let's style as our current banner (black & white with button). As for copy, I suggest the following -- which is an edit to @gdestuynder's: 

`We are currently experiencing an issue & working hard to resolve it. Please try to login again in a few minutes. <[arrow icon] Request Help>`

Is it possible for this suggested button to route to an open entry form or are all of our help request forms behind the login (eg; Hub)? 

The button could expand the banner & provide options like: sending an email to moc (ideally as a form but I realize that's a task) or going to Discourse (current `Need Help?` action at NLX bottom).

**Comment by hidde** [comment]
Thank you @m-branson, I will incorporate this copy.

Maybe the button can link either to the email address (maybe the one @gdestuynder mentions) or to the same Discourse page as the ‘Need help?’ link in the footer? 

Email works without login, if someone has an email client set up, Discourse needs registration, but that doesn't have to be with the account they're having trouble logging in with.

**Comment by gdestuynder** [comment]
In this case because this is a specific maintenance issue we might want to include the MOC as they handle availability problems/firehose

**Comment by gdestuynder** [comment]
![image](https://user-images.githubusercontent.com/956866/42594608-8feadb22-8504-11e8-9830-188ddf573914.png)
imported from Slack ;-)

**Comment by m-branson** [comment]
Great, in that case can we provide a button for each which will open the respective client if set up?

`We are currently experiencing an issue & working hard to resolve it. Please try to login again in a few minutes. Need help?`

`<Email> <Slack> <IRC>`

Similar to this...
<img width="645" alt="screen shot 2018-07-11 at 2 14 31 pm" src="https://user-images.githubusercontent.com/18686986/42599655-c9388d4c-8514-11e8-8c1c-c892eec85b48.png">

If not, perhaps just a second line with...
 `Request help via <moc@mozilla.com>, IRC #moc or Slack #it-all`

**Comment by hidde** [comment]
I'd like to go with the last suggestion, because the links to IRC and Slack won't necessarily work.

I found `#it-all` does not exist in Slack, should that be `#mozsm-all`? (Have asked this in mozsm-all channel just now)

**Comment by hidde** [comment]
Aligned with @andrew yesterday about best way to trigger this warning; we'll add it to the page in a `hidden` state, call a URL (which is set in the config/environment-specific variables), if that returns true, we unhide the warning.

**Comment by hidde** [comment]
With the _maintenance page_ [taken care of](https://github.com/mozilla-iam/auth0-deploy/blob/master/manual/maintenance.html), strictly in emergency cases only it temporarily replaces NLX, that leaves the scope of this issue to just the _maintenance banner_. (please correct if wrong @gdestuynder @andrewkrug).

**Comment by gdestuynder** [comment]
note, i used #servicedesk for slack in the mean time

**Comment by hidde** [comment]
Sometimes an idea looks good until you try it in code. The calling a URL part would require the URL to be set up somewhere, content to be hosted somewhere, it then to be correctly whitelisted in the CSP, seems like too many parts could go wrong, or we could forget to set them up.

Will just make it a config variable that we read out, so we ‘only’ have to build a new NLX with updated config when we need the maintenance banner. Let's keep this as simple as possible as we're unlikely to use it more than rarely.

**Comment by hidde** [comment]
This change is now in `master`, ready to be used when it is needed. Closing the issue.
