### ISSUE TITLE
action=signup bypasses querying for connection types

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/auth0-custom-lock#223]
With the addition of #212 it looks like when `action=signup` is passed to NLX from an RP, NLX doesn't respect the connection list that comes back from the `/connections` call that's made.

This manifests, for example, with Common Voice Dev. That RP passes [`action=signup`](https://auth-dev.mozilla.auth0.com/login?state=REDACTED&client=pl6mWaOtBMeXzTY3fUw57ED80bVkrgU1&protocol=oauth2&action=signup&response_type=code&redirect_uri=https%3A%2F%2Fvoice.allizom.org%2Fcallback&scope=openid%20email) to NLX and as a result is presented with all login options. The [connections call](https://auth-dev.mozilla.auth0.com/public/api/pl6mWaOtBMeXzTY3fUw57ED80bVkrgU1/connections) however shows that only passwordless and LDAP are allowed. If you remove the `action=signup` argument, NLX correctly renders the allowed connection types.

Please fix the new signup logic so that it respects the list of connections returned by the `/connections` endpoint

**Comment by hidde** [comment]
Fixed in NLX 1.5.1 (released on dev). We weren't passing through the filtering in the Sign Up flow, I have updated the code to go through the same filtering logic, it now respects the list of connections it is given.

**Comment by viorelaioia** [comment]
Looks good in https://voice.allizom.org/admin !
