### ISSUE TITLE
The auto-login shouldn't be active after a login error (to get the error twice)

### ISSUE THREAD

**Issue by rleitan** [mozilla-iam/auth0-custom-lock#231]
[Steps to reproduce]:
1.Go to https://web-mozillians-staging.production.paas.mozilla.community/en-US/
2.Click "Log in" button
3.Click "Continue with Github" button and enter the  valid credentials
4.Click "Go Back" button
5.Click "Log in" button

[Expected results]
3. Sorry, you may not login using GitHub. We require login to be performed using the most secure method available for your account, which is LDAP.  message should be displayed
4.The  https://web-mozillians-staging.production.paas.mozilla.community/en-US/ should be displayed
5. A  fresh NLX should be displayed. The auto-login should be not active after a login error

[Actual result]:
3. Sorry, you may not login using GitHub. We require login to be performed using the most secure method available for your account, which is LDAP.  message should be displayed
4.The  https://web-mozillians-staging.production.paas.mozilla.community/en-US/ is displayed
5. Sorry, you may not login using GitHub. We require login to be performed using the most secure method available for your account, which is LDAP.  message is displayed

**Comment by hidde** [comment]
Note that this happens only when the user has Auto-login enabled (between 4 and 5 in Actual result, Auto-login happens).

We cannot fix this issue in NLX, as NLX is not aware of these errors, as they happen after the authentication attempt, i.e. after NLX is shown. 

The suggested workaround for users is to try logging in one more time. At the second try, Auto-login will be disabled, as per the [only attempt Auto-login once per 10 minutes](https://github.com/mozilla-iam/auth0-custom-lock/blob/85963795e76a92e638cadf9fb7a753caa8306adc/src/js/decorators/filter-connections.js#L37)-rule .

**Comment by hidde** [comment]
Closing this issue as NLX already does what's technically possible to minimise the reported problem.
