### ISSUE TITLE
Add metrics for user's use of password managers

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/auth0-custom-lock#232]
In order to gather metrics on our users' use of password managers, I'd like to add a small test when they interact with the password field for LDAP login. I'd also like to emit the results of this test to Google Analytics.

Please add the following functionality to NLX. I've tested this with Lastpass and it correctly differentiates a human from Lastpass.

# Add Google Analytics

Add in Google Analytics using a Do Not Track respecting wrapper.

The GA code [looks like this](https://gist.github.com/gene1wood/9bc0ad280f72b8a41011c6f28fd5b628#file-detect-password-manager-html-L8-L17).

Our GA tracking code for NLX is `UA-84301250-4`. If you don't have access to our Mozilla Google Analytics let me know and I can probably help get you access.

The Mozilla recommended way to wrap this to respect DNT is [described here by Schalk Neethling](https://web.archive.org/web/20180128083757/http://schalkneethling.github.io/blog/2015/11/06/respect-user-choice-do-not-track/) (Shalk had me use archive.org while he figures out why his blog is down).

I don't know if you want to use his dnt-helper script or just incorporate the logic into NLX.

One thing I see missing from these examples is what to do so that the `ga` method which is called later doesn't cause an error as if DNT is set to yes, the `ga` method won't be defined.

# Record the password entry timing

In my code I'm using jQuery to create an event triggered function on keypress in the password field. If we don't use jQuery I'm assuming it's trivial to do this without it.

[Record the epoch time when the user first types a key in the field and when they last type a key](https://gist.github.com/gene1wood/9bc0ad280f72b8a41011c6f28fd5b628#file-detect-password-manager-html-L50-L59). This is to accommodate password managers that actually type keys.

[Some password managers don't even trigger keypresses which makes it all the easier](https://gist.github.com/gene1wood/9bc0ad280f72b8a41011c6f28fd5b628#file-detect-password-manager-html-L62-L66)

# Check the timing and emit the metric

When the user submits their LDAP password, [check the timing of the keypresses you've recorded and emit events to GA](https://gist.github.com/gene1wood/9bc0ad280f72b8a41011c6f28fd5b628#file-detect-password-manager-html-L61-L79)

I'm proposing an [`eventCategory`](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#eventCategory) of `ldap-login-form` and [`eventAction`s](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#eventAction) of `machine-typed-password` and `human-typed-password`. Feel free to suggest better ideas.

**Comment by hidde** [comment]
Thanks @gene1wood. I'll try and implement this GA event in the current sprint. 

NLX has a `fireGAEvent()` helper function which we can use for this; it only runs if Google Analytics was initialised (which is only the case when user does not have Do Not Track enabled… sorry for the double negation).

cc @hmitsch

**Comment by hidde** [comment]
Our current `eventCategory`s are: 
* Screen change (e.g. Continued as LDAP)
* Auto-login (e.g.  Already auto-logged in, aborting)
* Hiding (e.g. Hiding Firefox Accounts, as it is unsupported)
* Security (e.g. NLX was loaded inside an iframe)
* Autorisation (e.g. Authorising with GitHub)

For this particular use case, I would suggest this:

eventCategory | eventAction
---------------|-----------
Password entry | Manual
Password entry | Machine

**Comment by hmitsch** [comment]
These GA category and actions look great!

**Comment by hidde** [comment]
@gene1wood's heuristic is now implemented and visible in staging. This can be tested, because our Google Analytics functionality will: 

* in staging: log to the Dev Tools console
* in production: send an event to Google Analytics

(ie whatever you see appear in Dev Tools in staging, will be logged in GA for users that have DNT disabled).

I find it recognises LastPass input as 'machine', but 1Password as 'human'.

**Comment by hmitsch** [comment]
@gene1wood I am a 1Password user. If you want, we can look at this during my (late) evening hours.

**Comment by hidde** [comment]
I've just readded the code that logs key presses and start/end to the Console in the browser Dev Tools, for easier debugging.

**Comment by hmitsch** [comment]
I can confirm. My 1Password is also recognized as `human`. 😢 

<img width="659" alt="image" src="https://user-images.githubusercontent.com/869692/47373765-c4f7cc00-d6ec-11e8-97fd-2cd9af1082dd.png">

**Comment by rleitan** [comment]
Metrics for user's use of password managers testing on Mac (Safari) is blocked because of bug https://github.com/mozilla-iam/auth0-custom-lock/issues/239

**Comment by gene1wood** [comment]
This is what console output is for a lastpass filled login

# Lastpass

![Lastpass](https://i.imgur.com/TbWOVHE.png)

# 1Password

![1Password](https://i.imgur.com/UPw7CLG.png)

@hidde As someone who understands the flow a bit better, do these vastly different console outputs between lastpass and 1password reveal anything to you?

**Comment by gene1wood** [comment]
I've resolved the issue with 1Password and the new code is live in dev.

What's the process to get this code that is in the 'development' branch into 'master' and later production?

@hidde 
Should I make a new PR against master? Or do we sqauash or cherry pick from `development` into `master`?

**Comment by gene1wood** [comment]
This is now live in production
