### ISSUE TITLE
Autologin is broken in dev

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/auth0-custom-lock#247]
It does not autologin if you use testrp even with auto login on
I'm not sure why, the code is a little harder to trace on the cdn

**Comment by gene1wood** [comment]
I've been unable to reproduce this on my machine today. I've tried deleting local storage and haven't managed to trigger it.

**Comment by gdestuynder** [comment]
its unbroken with the update of dev code
i consider this solved by re-deploying dev
