### ISSUE TITLE
When visiting a new RP when already logged into auth0, login page is shown

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/auth0-custom-lock#25]
# Steps to reproduce

1. Log into https://phonebook.mozilla.org/
2. Browse to https://pto.mozilla.org/

# Expected results

Some kind of progress indicator showing that you're being redirected to pto.mozilla.org

# Actual results

The user is presented with the NLX "enter your email address" field. As the user begins to type in their email address the page redirects. The slower the users connection the worse this is.

**Comment by claudijd** [comment]
Observed the same behavior today.

**Comment by gdestuynder** [comment]
its been fixed as a hotfix, shows some indicator. its not great, but its there now.

https://github.com/mozilla-iam/auth0-custom-lock/issues/32 or https://github.com/mozilla-iam/auth0-custom-lock/issues/26 would be better solutions

**Comment by gene1wood** [comment]
What was the hotfix and when did it go live in prod?

When I go to pto.mozilla.org I see the same behavior currently.

**Comment by claudijd** [comment]
I too observed similar jarring 302 user experience this morning.

**Comment by hidde** [comment]
This has been fixed in PR #39 and that fix will be part of our next deploy.
