### ISSUE TITLE
1Password: Password entry - Human when Enter button is selected using keyboard

### ISSUE THREAD

**Issue by rleitan** [mozilla-iam/auth0-custom-lock#257]
[Prerequisites]:
Install 1Password and save an email address +password

[Steps to reproduce]:
1.Open https://aai-low-social-ldap-pwless.testrp.security.allizom.org/
2.Click "Log in with email" field and select an account saved in 1Password
3.Press Enter key
4.After the LDAP password is automatically filed by 1Password press Enter key

[Expected result]:
Password entry - Machine

[Actual result]:
Password entry - Human

[Note]:
The issue is not reproducible if the Enter button is clicked using the mouse

**Comment by gene1wood** [comment]
Good catch! Yup, I bet it counts the enter key as a keypress which causes the end time of the timer to be over 200ms.

We'll need to fix this.

**Comment by gene1wood** [comment]
@rleitan I've merged a bugfix in #259 for this that was deployed in auth0-dev 1 minute ago. This should address the bug you found.

**Comment by rleitan** [comment]
The issue is verified fixed!
