### ISSUE TITLE
NLX is displayed twice

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/auth0-custom-lock#26]
# Steps to reproduce

1. Browse to https://sso.mozilla.com/
2. Click your avatar and log out
3. Browse to https://pto.mozilla.org/

# Expected results

The NLX is displayed once

# Actual results

The NLX is displayed then the user is redirected back to the NLX and it's displayed a second time.

[![NLX Displayed Twice](https://img.youtube.com/vi/SwlW4-Y-Gpo/0.jpg)](https://www.youtube.com/watch?v=SwlW4-Y-Gpo)

I can provide an [HAR](https://en.wikipedia.org/wiki/.har) file if needed

**Comment by gdestuynder** [comment]
I believe this is expected behavior, though due to another bug it makes this weird "double display" refresh which we do not want

**Comment by gene1wood** [comment]
> basically the hot fix introduced a bug

When was the hot fix introduced and what was it? This problem in the video was manifesting 24 hours ago (which I think is before any hot fix's)

**Comment by gdestuynder** [comment]
indeed the behaviour is back

**Comment by andrewkrug** [comment]
keep in mind that sso.mozilla.com logout button is federated logout.

**Comment by gdestuynder** [comment]
it turns out the spinner comes on and off due to timing problems - leaving this open

**Comment by hidde** [comment]
This is now as good as it can be I believe.

Steps as above, results are now: 
* NLX is displayed, tries to autologin
* NLX is displayed again (as a result of autologin attempt, which is a redirect), does not autologin this time (because `tried_silent_auth=true` parameter is added), shows initial NLX screen

**Comment by gdestuynder** [comment]
AFAIK this is done :)
