### ISSUE TITLE
If LDAP is the only option, NLX should show an error if LDAP check fails

### ISSUE THREAD

**Issue by hidde** [mozilla-iam/auth0-custom-lock#27]
Or we end up with a screen that has no login options

**Comment by hidde** [comment]
Also, we should consider removing the word ‘or social options’ if all social options have been removed because of non-supporting RP.

**Comment by gene1wood** [comment]
>  we should consider removing the word ‘or social options’ if all social options have been removed because of non-supporting RP.

Good call, I opened #37 to capture this so it doesn't get lost in this issue talking about LDAP

**Comment by hidde** [comment]
We now show an error message if a user tries to login to a LDAP-only RP with an email address we cannot verify as LDAP. They also get the option to try a different email address.

<img width="546" alt="screen shot 2018-03-13 at 22 20 34" src="https://user-images.githubusercontent.com/178782/37370531-cc04371c-270c-11e8-85bc-94ea99a96d24.png">
