### ISSUE TITLE
Support ‘local’ environment for local development

### ISSUE THREAD

**Issue by hidde** [mozilla-iam/auth0-custom-lock#292]
Hi @gene1wood and @andrewkrug,

When the `environment` is set to `development`, which is the default, we're building paths to the CDN into NLX. 

Files only get to the CDN once changes are PR'ed, approved and merged. Ideally, people can see their changes locally before they go through those steps.

Proposed solution: we support a `local` environment which builds local paths into NLX, so that changes in HTML, CSS and JS are visible locally.

**Comment by hidde** [comment]
Wow. This is embarrassing, `./dmake start` does exactly this already, and in a better way. Will read better next time 😅

**Comment by hidde** [comment]
Hm ok, not completely. Even with `./dmake start`, changes made are updated in the local `dist` folder, but the HTML points to code on the CDN, so locally you would not see your updates until deployment.

What are your thoughts on adding a ‘local’ environment where the `cdn` variable is `''`, so that local files are shown?

**Comment by LeoMcA** [comment]
Oops, I did this here without realising this issue was open: https://github.com/mozilla-iam/auth0-custom-lock/commit/0733cc820e335e36c0e8c75e22405585ca5007af

**Comment by gene1wood** [comment]
@hidde Sorry I missed your at mention when you opened this.

**Comment by hidde** [comment]
All good, glad to read @LeoMcA has been able to fix it and do it better! 🥇
