### ISSUE TITLE
Only display options that are connections for RP

### ISSUE THREAD

**Issue by hidde** [mozilla-iam/auth0-custom-lock#3]
We used to be able to get a list of connections for an RP with `auth0.getConnections()` but that has been deprecated.

**Comment by gdestuynder** [comment]
there is an endpoint that is deprecated that can be directly queried as well.
that said, whichever solution we use, it would be good to also store the result in localstorage, such as

```
var s = window.localStorage;
s.setItem('connection', connection);
```

So that the auto-login code can do something like:

```
var connection s.getItem('connection');
if (connection !== null) {
  window.location.....+'&connection='+connection+...
}
```

so that auto-login works with all providers

**Comment by hidde** [comment]
This now works by calling the public connections endpoint .
