### ISSUE TITLE
NLX Mobile UI Refinement

### ISSUE THREAD

**Issue by m-branson** [mozilla-iam/auth0-custom-lock#30]
@hidde mobile UI could use some front-end love to be up to desktop visual standard (especially noticing this in Firefox). Seeing tense edge-to-edge width of the card and banner + browser default button/field styling (shadows + gradients).

Screenshot: iOS Firefox on iPhoneX
![sso-mobile](https://user-images.githubusercontent.com/18686986/36514485-6f9cc68a-1729-11e8-9d3f-9958f8d7a565.PNG)

**Comment by hidde** [comment]
Removed platform specific styling: https://github.com/mozilla-iam/auth0-custom-lock/commit/3d723d5fdb7c4569ec0b084e6b549c52a94851e9

Tweak banner and card styling on mobile and desktop: https://github.com/mozilla-iam/auth0-custom-lock/commit/4645ad3c54eda0263b228cba35b1929905b88d12
