### ISSUE TITLE
SSO 'Logout Success' requires front-end update 

### ISSUE THREAD

**Issue by m-branson** [mozilla-iam/auth0-custom-lock#31]
@hidde not sure if this screen technically 'lives within NLX' but from the UX standpoint it may as well be considered part of the same flow. As such, the UI requires updating to the current NLX style library. See attached mobile screen for reference (and note card width here for ideal mobile width ratios referenced in #30).

Also note issue is for all viewports, not just mobile.

![logout-ui-mobile](https://user-images.githubusercontent.com/18686986/36514667-5d3384ce-172a-11e8-924b-4bd63497ab08.PNG)

**Comment by gdestuynder** [comment]
this is an SSO Dashboard issue, if you wanna re-file it there cc @andrewkrug @m-branson

**Comment by m-branson** [comment]
Thanks @gdestuynder -- now submitted [here](https://github.com/mozilla-iam/sso-dashboard/issues/227).
