### ISSUE TITLE
Test for passwordless vs LDAP has bad regex causing mismatches

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/auth0-custom-lock#316]
[The regex which tests if an email address is an LDAP email address](https://github.com/mozilla-iam/auth0-custom-lock/blob/8cad825e945bb07bb10bae7c72b6f04bee6972ee/src/js/handlers/enter.js#L29) matches more broadly than it should.

This matches, for example, `test-mozilla.com-test@gmail.com`

Additionally, this method of determining if an email address is present in LDAP is very rudimentary and doesn't match LDAP users who have email addresses outside these limited set of domains, making it impossible for those users to login with LDAP despite being LDAP users.

A partial fix which at least resolves the overly broad match would be to change the regex to

```
  var qualifiesForLDAPShortcut = /(@mozilla\.com|@getpocket\.com|@mozillafoundation\.org)$/.test( emailField.value );
```

**Comment by LeoMcA** [comment]
@gene1wood lol have we got some kind of mind meld going on? https://github.com/mozilla-iam/auth0-custom-lock/commit/6cc0c909f89e5c63c50a0966ef1d7134a6c18d3a
