### ISSUE TITLE
Don't display "or social options" if there are no social options

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/auth0-custom-lock#37]
Currently NLX shows "or social options" in the interface even when there are no social options. Let's display this conditionally dependent on the login methods available.

Also, do users know what a "social option" is?

**Comment by hidde** [comment]
Fixed in https://github.com/mozilla-iam/auth0-custom-lock/commit/fbae4df1fefb0c7be160335ee10857f22179de78

**Comment by m-branson** [comment]
@gene1wood I believe we changed this language to third-party as well.

@hidde when we are hiding all third-party login methods, can we ensure the UI for them isn't displayed? Primarily noting the horizontal rule and extra padding...if no third-party logins are present all UI related to them should be hidden as well. If it is not, things appear potentially 'broken'.

**Comment by hidde** [comment]
@m-branson Great call, I have just reimplemented the horizontal rule and the padding slightly differently and it now doesn't show when there are no third party options (https://github.com/mozilla-iam/auth0-custom-lock/commit/8b40fcfd41a5d4f159c646405f8747b1f160da0a). This will be in NLX 1.1.0.
