### ISSUE TITLE
"Cannot GET /" Error shown when trying to autologin with email

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/auth0-custom-lock#48]
STR:
1. Login with email to mozillians.org 
2. Navigate to https://discourse.mozilla.org/ and click Log In / Sign Up button 

Expected:
User is auto logged in with email in discourse

Actual:
"Cannot GET /" error is shown.

![cannot get](https://user-images.githubusercontent.com/5293100/36675106-c20a9844-1b10-11e8-935c-b99a11a3ef6f.png)

**Comment by gdestuynder** [comment]
Note: Looked, this indeed cannot work with auto-login as auth0 will not keep a session up for passwordless users at this time - at least not through the way we do auto-login right now

**Comment by hidde** [comment]
We have turned off autologin for email login / Passwordless, so this no longer happens.
