### ISSUE TITLE
Send email button returned when trying to login with volunteer LDAP in moderator

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/auth0-custom-lock#49]
STR:
1. Navigate to https://moderator.mozilla.org/ (uses auth0 dev atm)
2. Click Login button
3. Enter volunteer LDAP email
4. Click Enter

Expected:
Password field is shown

Actual:
"Send me an email" button is shown

**Comment by hidde** [comment]
This happened because we were calling the wrong endpoint. Is now fixed, I am closing this.
