### ISSUE TITLE
The spinner is not spinning when doing the autologin

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/auth0-custom-lock#51]
The spinner is just displayed (no spinning) in latest FF release, FF Nightly, IE11, Safari. 
It works in Chrome.
See https://www.screencast.com/t/OVkDuBBXTR.

**Comment by hidde** [comment]
This seems to be a rendering performance issue. [Research](https://github.com/h5bp/lazyweb-requests/issues/103) has shown CSS can do better animation than SVG.

I have [changed](https://github.com/mozilla-iam/auth0-custom-lock/commit/1998317482758eacf5d13fbfa6c91f7face3b74a) our spinner to use CSS, this change will go into NLX 1.1.1.

**Comment by viorelaioia** [comment]
Verified, works as expected! Closing the bug.
