### ISSUE TITLE
Autologging message not shown on iOS device

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/auth0-custom-lock#53]
Tried this on an iPhone 7, iOS 11.2.5, latest Firefox release, Safari, Chrome.

STR:
1. Login to testrp.security.allizom.org with LDAP
2. Go to mozillians staging
3. Click Log In button

Expected:
Spinner and "Autologging in with Mozilla-LDAP-Dev" message is shown

Actual:
Spinner is shown, message is not displayed. See https://drive.google.com/file/d/1rJ_5fNraugjiNRWkuohE4IeQDPTBbDaW/view?usp=sharing

Note: the message is shown on Android device

**Comment by hidde** [comment]
I can reproduce this, but not fix it, unfortunately; the redirect seems to be instantiated faster than our code is able to display the message. Some browsers stop executing script once they've started the redirect, it seems.

Closing this issue if that's ok, feel free to reopen if not.
