### ISSUE TITLE
Autologin failure due to localStorage being cleared NLX 1.1.0, 1.1.2,1.1.3

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/auth0-custom-lock#58]
I'm unsure if this is the same problem as #35 but this one is reproducible consistently.

# Steps to reproduce

From a brand new profile/browser with no history/cache/cookies

1. Browse to https://sso.mozilla.com/
2. When prompted to login enter a mozilla.com email address
3. Enter that users LDAP password
4. Be logged in and presented with the dashboard
5. Browse to https://prod.testrp.security.allizom.org/

# Expected results

That the user would be auto logged in since they have a valid auth0 session

# Actual results

The user is presented with a NLX login prompt

This was observed on Feb 27 in Firefox 58.0.2+build1-0ubuntu0.16.04.1

**Comment by viorelaioia** [comment]
I was not able to reproduce this failure in NLX 1.1.0, I tried the steps in a new FF profile.

**Comment by gdestuynder** [comment]
Similar #59

**Comment by gdestuynder** [comment]
After a loooooooot of debugging heres my conclusions:

1) we need all GA events (and more) to echo to the console at least in dev.. pretty please @hidde 
2) localStorage is empty according to localStorage.getItem() *sometimes* when the auto login code triggers, and thus, it refuses  to auto login
3) I logged all setItem and removeItem calls i found and it does not see to remove the connection method from localStorage

Am not sure where the race condition happens, but it must be happening somewhere there

also
4) As per auth0 ticket, auth0 will honor `prompt` argument in this phase, so technically, we should replace `tried_silent_auth` by `prompt=none` (for "`tried_silent_auth=true`") and `promp=` (for "`tried_silent_auth=false`") as this is the OIDC standard for this

**Comment by hidde** [comment]
So as per the standard, Mozillians will need to use `prompt=none` for login/autologin if possible, `prompt=` for something else. 

Would it make sense to use `prompt=select_account` for the screen where users go from Mozillians if they need to add an identity? (i.e. adding their Google email?) If I read the spec correctly and interpret broadly that could be the right parameter?

**Comment by gdestuynder** [comment]
i made a quick xdotool loop to reproduce this and could not reproduce it on chromium. wondering if this is a firefox specific behavior

**Comment by hidde** [comment]
We now use `prompt=none` in addition to `tried_autologin` (previously known as `tried_silent_auth`).

**Comment by gdestuynder** [comment]
yup, sounds good! we still need to figure out why localstorage is cleared though

**Comment by gdestuynder** [comment]
possible fix as well, though slower:
Call this endpoint (with the correct client_id): `https://auth.mozilla.auth0.com/user/ssodata?client_id=UCOY390lYDxgj5rU8EeXRtN6EP005k7V`
this will return the last used connection as well

**Comment by gene1wood** [comment]
I experienced this again today.

# Steps to reproduce

* Clear everything from your browser (cookies localstorage)
* Browse to https://social-ldap-pwless.testrp.security.allizom.org/
* Login with LDAP
* Logout of the RP (leaving you logged into Auth0)
* Browse to https://ldap-pwless.testrp.security.allizom.org/
* Get autologged in
* Logout of the RP (leaving you logged into Auth0)
* Browse to https://social-pwless.testrp.security.allizom.org/

# Expected results

Get autologged in

# Actual results

Get a full NLX prompt without autologin

* Browse to https://social-pwless.testrp.security.allizom.org/
* Get a redirect to https://auth-dev.mozilla.auth0.com/authorize with GET query params
```
response_type=code
client_id=e2WKA3uaUj73a8MjB55jeb8DlAlWWE7e
state=c1d0bd52a164552eede96b2cebcba70c
redirect_uri=https%3A%2F%2Fsocial-pwless.testrp.security.allizom.org%2Fredirect_uri
prompt=
nonce=3ece41499d78efb91403ed94fd3064c5
scope=openid%20email%20profile
```
* Get a redirect to https://auth-dev.mozilla.auth0.com/login with GET query params
```
client=e2WKA3uaUj73a8MjB55jeb8DlAlWWE7e
protocol=oauth2
redirect_uri=https%3A%2F%2Fsocial-pwless.testrp.security.allizom.org%2Fredirect_uri
response_type=code
prompt=
nonce=3ece41499d78efb91403ed94fd3064c5
scope=openid%20email%20profile
state=xzwH1lC5yhUxkhMAd-Lbx9e306gNxDVl
```
* The NLX login ui is shown

**Comment by gene1wood** [comment]
Just saw this again today. Browsed to testrp RP in dev, got the NLX and logged in with GitHub, logged out of the RP, went back to the same RP and got the NLX instead of autologin.

Cleared everything in my profile.

Did the exact same sequence again, but this time on the visit to NLX after having logged out of the RP, NLX initiates the 302 to `/authorize` to do the autologin

**Comment by hidde** [comment]
@gdestuynder I tried using the `/ssodata` endpoint, as I think it could be a candidate to base our autologin decisions on, and used a client ID of an RP that I am logged in to. It returned a `404` and empty page.

Have you recently used the endpoint? The [Auth0 docs](https://auth0.com/docs/api-auth/intro) do say that it is deprecated

**Comment by gdestuynder** [comment]
@hidde `/ssodata` was disabled by auth0 very recently due to a security issue (public)
basically, this is no longer an option :(

**Comment by hidde** [comment]
@gdestuynder Ah, that's a bummer. 

Alternatively, (for the record in this issue): there was `getSSOData()` in auth0.js, but that has been deprecated. They recommend  using `checkSession()` instead but that does not return a most recent login method.

**Comment by gdestuynder** [comment]
or js cookies as per your idea

**Comment by gdestuynder** [comment]
agreed

**Comment by hidde** [comment]
As it is unlikely we will have time to further investigate this issue (also I think we tried our reasonable best), I'll mark this as WONTFIX.

**Comment by gene1wood** [comment]
I think once we have #133 we can understand how to fix this problem.
