### ISSUE TITLE
Logging out from RP produces odd autologin behavior on post 1.1.0 nlx

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/auth0-custom-lock#59]
1. https://social-ldap-pwless.testrp.security.allizom.org/
2. login w ldap
3. https://social-ldap-pwless.testrp.security.allizom.org/logout
4. https://social-ldap-pwless.testrp.security.allizom.org/
5. get autologged back in
6. https://social-ldap-pwless.testrp.security.allizom.org/logout
7. https://social-ldap-pwless.testrp.security.allizom.org/
8. get nlx prompt

**Comment by gdestuynder** [comment]
I can't reproduce on these links
i figure you hit your other bug again
for me, 8. auto logs in
