### ISSUE TITLE
After linking a new identity in mozillians, nlx tries to do the autologin with that identity 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/auth0-custom-lock#61]
STR:
1. Login to sso.mozilla.com with github
2. Click mozillians app -> you are autologged in with github
3. Add a new google identity
4. Go back to the dashboard and click Discourse

Expected:
User is autologged in with github

Actual:
User is autologged with google, as it remembers the most recent login type, which in this case is google. 

Note:
This affects volunteers that need to verify their google accounts, in order to get access to team drive.

**Comment by gdestuynder** [comment]
its known but we consider to be a thing to be fixed on mozillians.org - i suspect it has an issue already?
@akatsoulas @johngian

**Comment by gdestuynder** [comment]
Didnt find any to opened https://github.com/mozilla/parsys/issues/249

**Comment by hidde** [comment]
Actually, I think we can fix this in NLX.

What happens here is that NLX is saving the login method that user is trying to add in Mozillians. At next login, it is using that saved login method. 

Fix in NLX for this: don't save method if `account_linking=true` parameter exists in the URL (this  parameter exists andi is also used to turn off autologin and the shortcut-regex-match LDAP check, alo both things that account linking needs).

**Comment by gdestuynder** [comment]
i strongly suggest not to fix this in NLX, but in mozillians, specially together with https://github.com/mozilla-iam/auth0-custom-lock/issues/58#issuecomment-369424347 as this would be the standard-compliant way to do it.

**Comment by gdestuynder** [comment]
standard: https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest
https://openid.net/specs/openid-connect-core-1_0.html#Authenticates

**Comment by hidde** [comment]
@gdestuynder: While I agree Mozillians should be updated to use the standard params, it still makes sense imho to use the `account_linking` parameter in NLX to NOT store the used method in localStorage. Because storing would cause it to be reused next time, and that is this bug. What do you think?

**Comment by gdestuynder** [comment]
If NLX uses `prompt` as well there should be no problem, no?

**Comment by hidde** [comment]
The problem if, if someone verifies an account (say, Google) and that process involves NLX, then NLX will save that login method (Google). That means next time NLX is used for something else, the user may get autologged in using Google. 

This is regardless of whether `prompt` is used.

**Comment by gdestuynder** [comment]
`prompt=select_account` won't auto log you in with auth0, and if NLX supports `prompt` it will also not autolog you in

**Comment by hidde** [comment]
The saving wrong method bit is fixed in NLX, this can now be tested! (Mozillians have also started using `prompt=select_account` and NLX honours that)

**Comment by viorelaioia** [comment]
This is fixed in prod. After doing account linking in mozillians, the user will see the nlx form asking for credentials for any RP he/she navigates to. So autologin won't work first time the user sees nlx after account linking/upgrade. After entering credentials, autologin will work as expected.
