### ISSUE TITLE
Add link in footer of lock to changelog

### ISSUE THREAD

**Issue by andrewkrug** [mozilla-iam/auth0-custom-lock#67]
It would be great to have a link on the lock to go to the CHANGELOG.

**Comment by hidde** [comment]
Closing this for now as discussed in the Tech Alignment on 7 March.

To still make the changelog discoverable, I have added a link to it in the HTML code: https://github.com/mozilla-iam/auth0-custom-lock/commit/0c99a12b6a6d854b20f4c95b1c9e6c7cc33f214c
