### ISSUE TITLE
Lock should show current version in the corner of the page

### ISSUE THREAD

**Issue by andrewkrug** [mozilla-iam/auth0-custom-lock#68]
It would be nice to have a visual indicator in the lock.  Maybe something subtly showing the version in the lower right corner of the page.

**Comment by gene1wood** [comment]
Or a think that shows it on mouseover. It does currently show in the page source. We could also echo it to the javascript console.

**Comment by hidde** [comment]
Hm, it seems at yesterday's tech alignment we decided against this. I will leave it in the page source though, so that people still have a fairly easy way to access it. Closing this issue for now.
