### ISSUE TITLE
Cannot authenticate with "Enter" button if a previous LDAP login failed due to a wrong/mistyped password

### ISSUE THREAD

**Issue by caggle** [mozilla-iam/auth0-custom-lock#7]
Hi,

I noticed, if you choose to login with your @m.c. email address, which uses the LDAP connection type, and if you mistype your password, authentication (obviously) fails and the user sees a page similar to this:
![image](https://user-images.githubusercontent.com/30646014/35315938-1573e8d0-0123-11e8-9e1f-027afe366c2f.png)
The page clearly encourages the user to try again, with an input prompt. However, when the form is filled with presumably correct password and enter is clicked, the form is not submitted, nothing happens. The user needs to get back to the original page to try again by clicking "need to try again with a different account" link.

**Comment by hidde** [comment]
Thanks for reporting this. Fix coming up!

**Comment by hidde** [comment]
This has now been fixed in commit [e220c9677baf1731da01e0fa44feba6dea40776a](https://github.com/mozilla-iam/auth0-custom-lock/commit/e220c9677baf1731da01e0fa44feba6dea40776a)
