### ISSUE TITLE
account credentials often forgotten

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-iam/auth0-custom-lock#70]
Starting last Saturday (?), I often get logged out of Mozilla properties (once per day?) and have to enter login and password to get logged in again (the auto login doesn't kick in, obviously). Today it was with the latest Nightly and I had already used mana.mozilla.org, but one request suddenly wanted a new login.

**Comment by gene1wood** [comment]
I get the same thing and we've been investigating in #35
