### ISSUE TITLE
Replace brittle autologin.js query parameter transformation

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/auth0-custom-lock#86]
Please change this [url query parameter transformation code](https://github.com/mozilla-iam/auth0-custom-lock/blob/e07189ee2dc3c75db01b649308d1cbc3ec860db6/src/js/helpers/autologin.js#L10) to something more durable that doesn't depend on the order of the query parameters.

I'd recommend
* Parsing the url to extract all query parameters
* Doing the needed transformations of the parameters
* Rebuilding the transformed parameters into a new URL

Here's some [example code](https://stackoverflow.com/a/901144/168874) that might inspire you

This was identified in #85

**Comment by hidde** [comment]
We can probably use the `buildAuthorizeUrl()` function that Auth0.js offers: https://auth0.github.io/auth0.js/global.html#buildAuthorizeUrl

**Comment by gene1wood** [comment]
Sounds like this is fixed in #126
