### ISSUE TITLE
prompt=none in 1.1.2 is passed onto Google breaking Google autologin

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/auth0-custom-lock#87]
# Steps to reproduce

Have an active Auth0 session based off of Google
Logout of Google so you don't have a valid Google session

* Browse to https://social-ldap-pwless.testrp.security.allizom.org/
* Get redirected to https://auth-dev.mozilla.auth0.com/authorize with query params
```
response_type=code
client_id=pCGEHXW0VQNrQKURDcGi0tghh7NwWGhW
state=878a4270a436449155b3d07cc89e3a26
redirect_uri=https%3A%2F%2Fsocial-ldap-pwless.testrp.security.allizom.org%2Fredirect_uri
prompt=
nonce=081b6cf331da73a1871e67acad01ff8c
scope=openid%20email%20profile
```
* Get redirected to https://auth-dev.mozilla.auth0.com/login with query params
```
client=pCGEHXW0VQNrQKURDcGi0tghh7NwWGhW
protocol=oauth2
redirect_uri=https%3A%2F%2Fsocial-ldap-pwless.testrp.security.allizom.org%2Fredirect_uri
response_type=code
prompt=
nonce=081b6cf331da73a1871e67acad01ff8c
scope=openid%20email%20profile
state=eNemoCZRvJhDlEIKxBwpK0jQ6aobALY6
```

# Expected results

* Call https://auth-dev.mozilla.auth0.com/authorize with query params
```
client_id=pCGEHXW0VQNrQKURDcGi0tghh7NwWGhW
protocol=oauth2
redirect_uri=https%3A%2F%2Fsocial-ldap-pwless.testrp.security.allizom.org%2Fredirect_uri
response_type=code
nonce=081b6cf331da73a1871e67acad01ff8c
scope=openid%20email%20profile
state=eNemoCZRvJhDlEIKxBwpK0jQ6aobALY6
sso=true
connection=google-oauth2
prompt=none
tried_autologin=true
```
* Get redirected to Google https://accounts.google.com/o/oauth2/auth with query params
```
response_type=code
redirect_uri=https%3A%2F%2Fauth-dev.mozilla.auth0.com%2Flogin%2Fcallback
scope=email%20profile
state=nomqyqdDnBVA6NG138MzGW_YZy-1js9Q
client_id=882664650006-aik4rn0nktr993bl47rshuv62as4p11k.apps.googleusercontent.com
```
* Google sees that the user isn't logged int and presents them with an account chooser or login prompt

# Actual results

* Call https://auth-dev.mozilla.auth0.com/authorize with query params
```
client_id=pCGEHXW0VQNrQKURDcGi0tghh7NwWGhW
protocol=oauth2
redirect_uri=https%3A%2F%2Fsocial-ldap-pwless.testrp.security.allizom.org%2Fredirect_uri
response_type=code
nonce=081b6cf331da73a1871e67acad01ff8c
scope=openid%20email%20profile
state=eNemoCZRvJhDlEIKxBwpK0jQ6aobALY6
sso=true
connection=google-oauth2
prompt=none
tried_autologin=true
```
* Get redirected to Google https://accounts.google.com/o/oauth2/auth with query params
```
prompt=none
response_type=code
redirect_uri=https%3A%2F%2Fauth-dev.mozilla.auth0.com%2Flogin%2Fcallback
scope=email%20profile
state=nomqyqdDnBVA6NG138MzGW_YZy-1js9Q
client_id=882664650006-aik4rn0nktr993bl47rshuv62as4p11k.apps.googleusercontent.com
```
* Google sees `prompt=none` and redirects to https://auth-dev.mozilla.auth0.com/login/callback with query params
```
state=nomqyqdDnBVA6NG138MzGW_YZy-1js9Q
error_subtype=access_denied
error=immediate_failed
```

Notice that auth0 passes `prompt=none` onto Google when we send it to them in the `/authorize` call.

# What to do

Since Auth0 passes `prompt=none` along, this breaks things. I don't think we can pass `prompt=none` to auth0 in the `/authorize` call from `/login`

**Comment by gdestuynder** [comment]
Fixed in 1.1.3
The fix ain't great as it effectively removes `prompt` support, but it keeps auto-login functional until we make a better fix
cc @hidde
