### ISSUE TITLE
Google and Github images seem to be missing 1 line of 1 pixel at the top

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/auth0-custom-lock#95]
It looks like they're chopped off - directly in the svg, for some reason
assigning to you @hidde because you might know why that is better than me, else i'd basically replace them

**Comment by m-branson** [comment]
Thanks @gdestuynder -- this looks 'new' to me, haven't noticed it prior to today.

**Comment by hidde** [comment]
This is now fixed!
