### ISSUE TITLE
During NLX autologin makes an unecesary call to Auth0 /connections endpoint is made

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/auth0-custom-lock#97]
In NLX 1.1.5 when a user is being autologged in and no list of connections need be shown to them (because they're being autologged in), the call to the Auth0 `/connections` endpoint is still being made. This call doesn't need to be made because NLX is not showing a list of connection types to the user

https://auth-dev.mozilla.auth0.com/public/api/..redacted../connections

NLX should only call the `/connections` endpoint when NLX is called with `tried_autologin=true` as a query parameter, otherwise the call to `/connections` should not be made.

**Comment by gene1wood** [comment]
In talking with @gdestuynder it sounds like one of reasons for this call to `/connections` is to determine if the RP supports the connection type before attempting auto login because, natively, when Auth0 gets a login attempt to an RP with a disallowed connection type, Auth0 either redirects the user back to the RP with error params or it just shows an error page on Auth0 at the `/authorize` endpoint.

If mozilla-iam/auth0-deploy#187 is successful we can do this check as an Auth0 rule instead of in NLX and save the user the delay of the `/connections` call.

**Comment by hidde** [comment]
Unfortunately, mozilla-iam/auth0-deply/#187 was unsuccessful, so for now let's keep the `/connections` call. Closing this issue.
